name: "Hello"

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Mate!"
      - name: Dame la fecha
        run: date
      - name: Buscando archivos
        run: ls -l
